// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: furniture_app
  static const package = "furniture_app";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName})
      : assert(assetName != null);

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: lib/assets/images/img_banner_1.png
  // ignore: non_constant_identifier_names
  final img_banner_1 = const AssetResource("assets/images/img_banner_1.png",
      packageName: R.package);

  /// asset: lib/assets/images/img_poduct_1.png
  // ignore: non_constant_identifier_names
  final img_poduct_1 = const AssetResource("assets/images/img_poduct_1.png",
      packageName: R.package);

  /// asset: lib/assets/images/img_product_2.png
  // ignore: non_constant_identifier_names
  final img_product_2 = const AssetResource("assets/images/img_product_2.png",
      packageName: R.package);

  /// asset: lib/assets/images/img_product_2_1.png
  // ignore: non_constant_identifier_names
  final img_product_2_1 = const AssetResource(
      "assets/images/img_product_2_1.png",
      packageName: R.package);

  /// asset: lib/assets/images/img_product_2_2.png
  // ignore: non_constant_identifier_names
  final img_product_2_2 = const AssetResource(
      "assets/images/img_product_2_2.png",
      packageName: R.package);

  /// asset: lib/assets/images/img_product_2_3.png
  // ignore: non_constant_identifier_names
  final img_product_2_3 = const AssetResource(
      "assets/images/img_product_2_3.png",
      packageName: R.package);

  /// asset: lib/assets/images/img_product_2_4.png
  // ignore: non_constant_identifier_names
  final img_product_2_4 = const AssetResource(
      "assets/images/img_product_2_4.png",
      packageName: R.package);

  /// asset: lib/assets/images/img_product_2_5.png
  // ignore: non_constant_identifier_names
  final img_product_2_5 = const AssetResource(
      "assets/images/img_product_2_5.png",
      packageName: R.package);

  /// asset: lib/assets/images/img_product_3.png
  // ignore: non_constant_identifier_names
  final img_product_3 = const AssetResource("assets/images/img_product_3.png",
      packageName: R.package);

  /// asset: lib/assets/images/img_product_4.png
  // ignore: non_constant_identifier_names
  final img_product_4 = const AssetResource("assets/images/img_product_4.png",
      packageName: R.package);

  /// asset: lib/assets/images/img_user.png
  // ignore: non_constant_identifier_names
  final img_user =
      const AssetResource("assets/images/img_user.png", packageName: R.package);
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();

  /// asset: lib/assets/images/ic_arrow_back.svg
  // ignore: non_constant_identifier_names
  final ic_arrow_back = const AssetResource("assets/images/ic_arrow_back.svg",
      packageName: R.package);

  /// asset: lib/assets/images/ic_bag.svg
  // ignore: non_constant_identifier_names
  final ic_bag =
      const AssetResource("assets/images/ic_bag.svg", packageName: R.package);

  /// asset: lib/assets/images/ic_bag_active.svg
  // ignore: non_constant_identifier_names
  final ic_bag_active = const AssetResource("assets/images/ic_bag_active.svg",
      packageName: R.package);

  /// asset: lib/assets/images/ic_bookmark.svg
  // ignore: non_constant_identifier_names
  final ic_bookmark = const AssetResource("assets/images/ic_bookmark.svg",
      packageName: R.package);

  /// asset: lib/assets/images/ic_cart.svg
  // ignore: non_constant_identifier_names
  final ic_cart =
      const AssetResource("assets/images/ic_cart.svg", packageName: R.package);

  /// asset: lib/assets/images/ic_home.svg
  // ignore: non_constant_identifier_names
  final ic_home =
      const AssetResource("assets/images/ic_home.svg", packageName: R.package);

  /// asset: lib/assets/images/ic_home_active.svg
  // ignore: non_constant_identifier_names
  final ic_home_active = const AssetResource("assets/images/ic_home_active.svg",
      packageName: R.package);

  /// asset: lib/assets/images/ic_menu.svg
  // ignore: non_constant_identifier_names
  final ic_menu =
      const AssetResource("assets/images/ic_menu.svg", packageName: R.package);

  /// asset: lib/assets/images/ic_minus.svg
  // ignore: non_constant_identifier_names
  final ic_minus =
      const AssetResource("assets/images/ic_minus.svg", packageName: R.package);

  /// asset: lib/assets/images/ic_more.svg
  // ignore: non_constant_identifier_names
  final ic_more =
      const AssetResource("assets/images/ic_more.svg", packageName: R.package);

  /// asset: lib/assets/images/ic_plus.svg
  // ignore: non_constant_identifier_names
  final ic_plus =
      const AssetResource("assets/images/ic_plus.svg", packageName: R.package);

  /// asset: lib/assets/images/ic_remove.svg
  // ignore: non_constant_identifier_names
  final ic_remove = const AssetResource("assets/images/ic_remove.svg",
      packageName: R.package);

  /// asset: lib/assets/images/ic_search.svg
  // ignore: non_constant_identifier_names
  final ic_search = const AssetResource("assets/images/ic_search.svg",
      packageName: R.package);
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: lib/assets/images/img_banner_1.png
  // ignore: non_constant_identifier_names
  AssetImage img_banner_1() {
    return AssetImage(asset.img_banner_1.keyName);
  }

  /// asset: lib/assets/images/img_poduct_1.png
  // ignore: non_constant_identifier_names
  AssetImage img_poduct_1() {
    return AssetImage(asset.img_poduct_1.keyName);
  }

  /// asset: lib/assets/images/img_product_2.png
  // ignore: non_constant_identifier_names
  AssetImage img_product_2() {
    return AssetImage(asset.img_product_2.keyName);
  }

  /// asset: lib/assets/images/img_product_2_1.png
  // ignore: non_constant_identifier_names
  AssetImage img_product_2_1() {
    return AssetImage(asset.img_product_2_1.keyName);
  }

  /// asset: lib/assets/images/img_product_2_2.png
  // ignore: non_constant_identifier_names
  AssetImage img_product_2_2() {
    return AssetImage(asset.img_product_2_2.keyName);
  }

  /// asset: lib/assets/images/img_product_2_3.png
  // ignore: non_constant_identifier_names
  AssetImage img_product_2_3() {
    return AssetImage(asset.img_product_2_3.keyName);
  }

  /// asset: lib/assets/images/img_product_2_4.png
  // ignore: non_constant_identifier_names
  AssetImage img_product_2_4() {
    return AssetImage(asset.img_product_2_4.keyName);
  }

  /// asset: lib/assets/images/img_product_2_5.png
  // ignore: non_constant_identifier_names
  AssetImage img_product_2_5() {
    return AssetImage(asset.img_product_2_5.keyName);
  }

  /// asset: lib/assets/images/img_product_3.png
  // ignore: non_constant_identifier_names
  AssetImage img_product_3() {
    return AssetImage(asset.img_product_3.keyName);
  }

  /// asset: lib/assets/images/img_product_4.png
  // ignore: non_constant_identifier_names
  AssetImage img_product_4() {
    return AssetImage(asset.img_product_4.keyName);
  }

  /// asset: lib/assets/images/img_user.png
  // ignore: non_constant_identifier_names
  AssetImage img_user() {
    return AssetImage(asset.img_user.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();

  /// asset: lib/assets/images/ic_arrow_back.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_arrow_back({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_arrow_back.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/ic_bag.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_bag({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_bag.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/ic_bag_active.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_bag_active({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_bag_active.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/ic_bookmark.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_bookmark({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_bookmark.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/ic_cart.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_cart({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_cart.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/ic_home.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_home({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_home.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/ic_home_active.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_home_active({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_home_active.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/ic_menu.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_menu({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_menu.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/ic_minus.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_minus({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_minus.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/ic_more.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_more({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_more.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/ic_plus.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_plus({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_plus.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/ic_remove.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_remove({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_remove.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/ic_search.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_search({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_search.keyName, width: width, height: height);
    return imageProvider;
  }
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();

  /// font family: playfair
  // ignore: non_constant_identifier_names
  final playfair = "playfair";

  /// font family: spartan
  // ignore: non_constant_identifier_names
  final spartan = "spartan";
}
